### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by Solido** [davidmarne/built_redux#10]
I've started a project on Flutter and I'm really interested in build_redux ( and frankly all the built_philosophy ), is this a acceptable to start a project on this lib ? question is mainly about support of the lib ? 

Thank you David

**Comment by davidmarne** [comment]
Hey Solido, great to see some interest!

To answer your questions, I do not see any reason you could not start consuming right now. I believe the existing implementation does provide a functional platform to start developing on.

It is still pre 1.0, so as of right now I cannot guarantee any breaking changes will not be introduced. However, I think I am pretty close to making that 1.0 tag and once I do I will follow semantic versioning.

As far as support goes, the library itself is small and very simple and I believe once a 1.0 tag is made support will mainly be making sure its dependencies do not go stale. 

I will be happy to consider feature requests, address questions/issues, and contributions from the community are welcome as well.

**Comment by davidmarne** [comment]
So i looked a flutter a bit and it seems like a good candidate for built_redux.

I'll try and look into making library similar to flutter_flux over the next week. 
https://github.com/flutter/flutter_flux

**Comment by davidmarne** [comment]
@Solido  I started up this library today, and got a working example! See:
https://github.com/davidmarne/flutter_built_redux

Still need to write better documentation then i will release it and push it to the pub registry.
I'm going to close this issue now, so keep your eye on https://github.com/davidmarne/flutter_built_redux for further progress.
