### ISSUE TITLE
Async actions

### ISSUE THREAD

**Issue by xenolf** [davidmarne/built_redux#12]
Redux.js has this feature which makes it pretty easy to interact with something like an network request. Will this library support that? Or what is the recommended way of interacting with async state changes?

**Comment by davidmarne-wf** [comment]
The best way to perform async operations is via middleware. For example:
```dart
 var networkMiddleware =  (new MiddlwareBuilder<Counter, CounterBuilder, CounterActions>()
      ..add<int>(AppActionNames.someAction, _handlerThatRunsAsyncCode)).build();

_handlerThatRunsAsyncCode(MiddlewareApi<App, AppBuilder, AppActions> api, ActionHandler next, Action<int> action) {
  var url = "http://my-server.com";
  // call the web server asynchronously
  HttpRequest.getString(url).then(api.actions.onRequestResolved);
}
```

What this is doing is listening for the action 'someAction' to be dispatched. When it is dispatched _handlerThatRunsAsyncCode will be called which can perform some async operation. When that operation resolves it dispatches a new action, 'onRequestResolved'. The payload to onRequestResolved would be the result from the network request.

You then must make sure to include the networkMiddlware in the list of middleware passed to your store on instantiation, for example:
```dart
var store = new Store<App, AppBuilder, AppActions>(
  new App(),
  new AppActions(),
  middleware: [networkMiddleware],
);
```

**Comment by davidmarne** [comment]
The best way to perform async operations is via middleware. For example:
```dart
 var networkMiddleware =  (new MiddlwareBuilder<Counter, CounterBuilder, CounterActions>()
      ..add<int>(AppActionNames.someAction, _handlerThatRunsAsyncCode)).build();

_handlerThatRunsAsyncCode(MiddlewareApi<App, AppBuilder, AppActions> api, ActionHandler next, Action<int> action) {
  var url = "http://my-server.com";
  // call the web server asynchronously
  HttpRequest.getString(url).then(api.actions.onRequestResolved);
}
```

What this is doing is listening for the action 'someAction' to be dispatched. When it is dispatched _handlerThatRunsAsyncCode will be called which can perform some async operation. When that operation resolves it dispatches a new action, 'onRequestResolved'. The payload to onRequestResolved would be the result from the network request.

You then must make sure to include the networkMiddlware in the list of middleware passed to your store on instantiation, for example:
```dart
var store = new Store<App, AppBuilder, AppActions>(
  new App(),
  new AppActions(),
  middleware: [networkMiddleware],
);
```

**Comment by xenolf** [comment]
Thanks! That worked quite nicely.
