### ISSUE TITLE
Does not support built_value 7.0.0

### ISSUE THREAD

**Issue by maxlapides** [davidmarne/built_redux#132]
I think we just need to bump the version in `pubspec.yaml`

**Comment by IncPlusPlus** [comment]
It seems like this was resolved in #136 and has been fixed since [7.5.7](https://pub.dev/packages/built_redux/versions/7.5.7) (see the dependencies section of this page). Are you still experiencing this issue?

**Comment by maxlapides** [comment]
All good now, thanks!
