### ISSUE TITLE
support the new built_value version 4.0.0

### ISSUE THREAD

**Issue by zoechi** [davidmarne/built_redux#25]
I tried to have a closer look at this package, but it collides with the built_value version I'm using.

**Comment by davidmarne** [comment]
Unfortunately I am without a laptop until September 20th so you cannot expect a fix from me until then. However, if you are willing you can update the dependencies yourself and create a pr. So long as CI passes I will be happy to merge from mobile.
Looking at the built_value release you would have to update built_value, build, and build_runner in the pubspec as well as update the tool/build.dart file as described here:
https://github.com/google/built_value.dart/releases/tag/v4.0.0

**Comment by zoechi** [comment]
Thanks for your quick response.
I considered that. I do not know yet whether I get to it.

**Comment by davidmarne** [comment]
https://github.com/davidmarne/built_redux/pull/27
