### ISSUE TITLE
Consider making the payload to an ActionDispatcher optional

### ISSUE THREAD

**Issue by jacehensley-wf** [davidmarne/built_redux#31]
For cases where you just want to trigger an action that doesn't have a payload it would be nice to not have to pass in `null`

What are your thoughts?

**Comment by zoechi** [comment]
Would be great if there were a good way to not need to pass `null` when the generic type parameter is `Null`.

**Comment by davidmarne** [comment]
I'm cool with this. I'll get it in today.
