### ISSUE TITLE
built_redux example in "Flutter Architecture Samples"

### ISSUE THREAD

**Issue by brianegan** [davidmarne/built_redux#40]
Hey hey :)

I've been exploring different ways to do State Management in Flutter and decided I'd go ahead and build a "TodoMVC" type repo that showcases different architectures for the same app (a todo app, no surprises!).

I didn't know the best way to contact you, so I just thought I'd pop an issue in here. I'm trying to make sure the Architecture Samples are high quality and reflect your vision for how this library is meant to be used, so I'd love it if you had any feedback on the code I've written. I've also included a comparison to normal `Redux` and want to make sure you find the comparison fair, so please feel free to comment on the README as well!

https://gitlab.com/brianegan/flutter_architecture_samples/tree/master/example/built_redux

Happy to accept Merge Requests or chat more here with how it could be improved.

Best,
Brian

**Comment by davidmarne** [comment]
Hey Brian, this is awesome!  I got a chance to look over the examples and the built_redux one looks great. You got the built value serializers, enums, and everything! I do have a couple suggestions and I'd love to contribute. I'll throw up a merge request when I can get to it.

The README is on point, you described the differences very well.

**Comment by brianegan** [comment]
Sounds great! No rush of course, whenever you have a few minutes I'd love to see the suggestions.
