### ISSUE TITLE
Add support for tracing every action

### ISSUE THREAD

**Issue by patkujawa-wf** [davidmarne/built_redux#62]
E.g. by adding an optional [tracing](http://opentracing.io/) `Span` on `ActionDispatcher` or `Action`.

**Comment by davidmarne** [comment]
I don't think that really belongs in the core built_redux library. 
I suggest you write your own middleware that traces every action.
```dart
NextActionHandler tracingMiddleware(MiddlewareApi api) =>
    (ActionHandler next) => (Action action) {
        final span = tracer.startSpan(action.name);
        next(action);
        span.finish();
    };
```

**Comment by patkujawa-wf** [comment]
That's a good idea, but it wouldn't work for my purposes. I'd like the tracing to go as deep as it needs to, so the action handler could pass the trace to its child, ad nauseum, and the trace would capture everything. This proposal only traces the top-level action.

For example, if my action kicks off a server call, which kicks off several other server calls, none of those could be included in this trace.

**Comment by davidmarne** [comment]
Sorry forgot to circle back on this.

You're right, my suggestion doesn't work for your use case, but I still don't think that really belongs in the core built_redux library. I would like to keep the dependencies as minimal as possible.

I think your best bet is to just create a payload class that you can extend that does what you would like :/

```dart
@immutable
abstract class TracingActionPayload {
  final Span span = tracer.startSpan('span name');
}

@immutable
class ConcretePayload extends TracingActionPayload {
  final String otherPayload;
  ConcretePayload(this.otherPayload);
}

abstract class AppActions extends ReduxActions {
  ActionDispatcher<ConcretePayload> get myAction;
}

final actions = new AppActions();

actions.myAction(new ConcretePayload('some value'));
```
