### ISSUE TITLE
build.dart example doesn't work with current versions

### ISSUE THREAD

**Issue by jermahs** [davidmarne/built_redux#71]
I used your package 7.4.1-dev and I'm having an issue setting up the build/watch.dart files as it seems the `build` and `watch` functions have changed. I tried looking around for some documentation, but I can't seem to find anything. 

I was hoping you could either 1) point me in the right direction to figure this out or 2) provide an example of an updated build.dart file. 

I followed Brian Egan's example and placed the file in `tool/build.dart` with the following attempted code:

```dart
import 'dart:async';

import 'package:build_runner/build_runner.dart';
import 'package:built_value_generator/built_value_generator.dart';
import 'package:source_gen/source_gen.dart';
import 'package:built_redux/generator.dart';

Future main(List<String> args) async {
  await watch([
    new BuilderApplication.forBuilder('veoci', [
        (options) => new PartBuilder([
          new BuiltValueGenerator(),
          new BuiltReduxGenerator()
        ])
    ], (PackageNode node) {
      print('$node');
      return false;
    })
  ], deleteFilesByDefault: true);
}
```

I get an error when running it with `dart tool/build.dart`

```
'package:build/src/builder/post_process_build_step.dart': error: line 17 pos 32: ',' or ')' expected
        void Function(AssetId) addAsset,
```

Any advice would be greatly appreciated.

**Comment by davidmarne** [comment]
Yup, just to to be clear, you do not need to write a build.dart with the dev branch.
As per the [dev branch README](https://github.com/davidmarne/built_redux/tree/dart-2-dev), adding a build.yaml to the root of your project, with the following

```yaml
targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: false
``` 

Should get you going. Then all you need to do is run `pub run build_runner build` to build the generated models.
