### ISSUE TITLE
Generator and ValueBuilders

### ISSUE THREAD

**Issue by GRouslan** [davidmarne/built_redux#74]
I am using a [built_redux_repatch](https://github.com/davidmarne/built_redux_repatch) with a dev brunch. The BuiltReduxGenerator does not recognize ValueBuilders. For a example: 

`ActionDispatcher<Repatch<AppState, AppStateBuilder>> repatchDispatcher;`

leads to:

```
  final ActionDispatcher<dynamic Function(AppState, dynamic)>
      repatchDispatcher =
      new ActionDispatcher<dynamic Function(AppState, dynamic)>(
          'AppActions-repatchDispatcher');
```

Not generated class instead of a builder generates fine:

`ActionDispatcher<Repatch<AppState, AppState>> repatchDispatcher;`

leads to:

```
  final ActionDispatcher<dynamic Function(AppState, AppState)>
      repatchDispatcher =
      new ActionDispatcher<dynamic Function(AppState, AppState)>(
          'AppActions-repatchDispatcher');
```

**Comment by davidmarne** [comment]
https://github.com/davidmarne/built_redux/pull/84
