### ISSUE TITLE
increase upper bound for analyzer constraint

### ISSUE THREAD

**Issue by zoechi** [davidmarne/built_redux#76]
Flutter master v0.4.4 requires `analyzer: ^0.31.2-alpha.2`

**Comment by kostaa** [comment]
Hi, the latest flutter build comes with analyzer 0.32.3.
Any chance you could look into this please?

**Comment by davidmarne** [comment]
can do

**Comment by davidmarne** [comment]
https://github.com/davidmarne/built_redux/releases/tag/7.4.3-dev

**Comment by kostaa** [comment]
Great thanks!
