### ISSUE TITLE
version solving failing

### ISSUE THREAD

**Issue by dougdonohoe** [davidmarne/built_redux#87]
I'm trying to used latest 7.4.5 version of built_redux, but 'flutter packages upgrade' and 'flutter packages get' are failing.

This is one message:

```
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because XXX depends on build_runner >=0.9.0 which requires SDK version >=2.0.0-dev.61 <3.0.0, version solving failed.
```
I'm not sure how to upgrade the dart SDK - how is it that build_runner depends on a newer SDK?

If I add in this ```dev_dependencies:```

```
flutter_test:
   sdk: flutter
```

Then I get a different error:

```
Because no versions of built_value_generator match >6.0.0 <7.0.0 and built_value_generator 6.0.0 depends on analyzer ^0.32.1, built_value_generator ^6.0.0 requires analyzer ^0.32.1.
And because every version of flutter_test from sdk depends on analyzer 0.31.2-alpha.2, built_value_generator ^6.0.0 is incompatible with flutter_test from sdk.
So, because XXX depends on both flutter_test any from sdk and built_value_generator ^6.0.0, version solving failed.
```

I'm a little new to flutter, so wondering if you have any advice on the proper version to get things working?  

Here's output of flutter doctor:

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected devices (1 available)
```

**Comment by davidmarne** [comment]
Yea so I tried to update flutter_built_redux last night and ran into the same issue.
Flutter uses the latest version of analyzer on master, but not in the latest tag. Until flutter makes its next release I think using 7.4.5 of built_redux and 6.x.x of built_value is not gonna happen. 

The dependency on analyzer there is introduced by the latest version of source_gen which 7.4.5 of built_redux and 6.x.x of built_value both consume.

Hopefully with dart2 releasing yesterday the flutter team will get a release out soon and this will resolve itself.

**Comment by rockingdice** [comment]
Any updates on this?
Should I lower the versions of built_value and built_collection until there's a fix?

**Comment by davidmarne** [comment]
gonna close this, built_collection 4 works with [7.5.0](https://github.com/davidmarne/built_redux/releases/tag/7.5.0) and flutter_built_redux has been updated to allow sdk 2.0.0
