### ISSUE TITLE
Using the Navigator

### ISSUE THREAD

**Issue by mfulgo** [davidmarne/built_redux#92]
I'd like to find out if there is a prescribed way to use the `Navigator` when using `built_redux`.

I have a screen that has a button to trigger a call to the server - the button dispatches an `Action` that is handled by `Middleware`. The `Middleware` sends a request to the server and dispatches a success or error action depending on the result. I have reducers update the state depending on the result, which redraws the current screen. That's fine if the response was an error because we want to display it on the same screen.

However, if the server response was successful, I want to navigate to a different screen, but I haven't found a clean way to do that. (Creating a delayed future in the `StoreConnector` seems wrong, and calling the `Navigator` from the `build` method triggers an error.)

**Comment by mfulgo** [comment]
Looks like the approach for this is creating a `GlobalKey<NavigatorState>` and inject it into the middleware layer (or access it as a global, though that's less testable).

https://github.com/brianegan/flutter_redux/blob/simple-navigation-example/example/lib/main.dart#L20

Just have to remember to [set the key when creating the `MaterialApp`](https://github.com/brianegan/flutter_redux/blob/simple-navigation-example/example/lib/main.dart#L64).

Perhaps there's a good place to document this?

**Comment by davidmarne** [comment]
Hmm i'm not sure the best place to document this. Probably not here because this is pretty flutter specific and built_redux itself is platform agnostic, ie it works for vm, web, or flutter.

Maybe adding it to the example over at [flutter_built_redux](https://github.com/davidmarne/flutter_built_redux)?

**Comment by mfulgo** [comment]
Yes, good point that it's specific to Flutter; I think that would be a good place to put it. When we started trying to figure out these types of things, we found that the examples were just a little too bare-bones to answer some of these more in-depth types of issues.

I'll close the issue here and open one against that repo, referencing this one.
